version: "3.7"
services:
   mysqldb:
      restart: always
      image: mysql:5.7
#      build: 'mysql_database'
      environment:
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
         - "3307:3306"
      volumes:
         - mongo_database/my-db:/var/lib/mysql

   mongodb:
      image: mongo:latest
      restart: always
      environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      ports:
         - "27018:27017"